---
title: ' MEDB 5510Clinical Research Methods '
author: Simon
date: 2019-01-03
output:
  xaringan::moon_reader:
  lib_dir: libs
  nature:
    highlightStyle: github
    highlightLines: true
    countIncrementalSlides: false
---
#  Secondary Analysis 

+ **Definition – using existing database/dataset to re-examine variables and answer questions**
	+ **Research question different from what was originally addressed**
+ **Differences could be …**
	+ **Variables that are analyzed**
	+ **Relationships that are explored**
	+ **Different subsets of cases**
	+ **Different analysis techniques**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Could be done when able to combine different/compatible data sets**
+ **Advantages**
	+ **Cost**
	+ **Working with large dataset**
	+ **Time efficiency**
	+ **May be a good first step in a research area**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Disadvantages**
	+ **Lack of control over data collection process**
		+ **Quality control**
		+ **Specifics of variables and wording**
		+ **Missing data or data entry errors**
	+ **Consider possible sources of error**
		+ **Make judgment on possible impact on research question**
		+ **What can be done to address problems**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Two types of secondary data sets**
	+ **Individual**
	+ **Aggregate**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Individual – separate information available for each subject/unit**
	+ **Can use to measure associations between characteristics among individuals/units**
	+ **Source**
		+ **Previous research study**
		+ **Large regional and national data sets**
			+ **Surveillance, Epidemiology, and End Results (SEER)**
			+ **National Death Index**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Aggregate – information available only for groups of subjects**
+ **Can study associations among groups by comparing them on risk factors or variables of interest (ecologic studies)**
+ **Advantage – availability of data**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Aggregate (cont** **’** **d)**
+ **Disadvantage –**
	+ **Associations are especially susceptible to confounding**
	+ **Associations seen in aggregate don’t always hold at the individual level (ecologic fallacy)**
+ **Most appropriately used –**
	+ **Test the plausibility of a new hypothesis, or**
	+ **Generate new hypotheses**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Chicken or the egg!**
	+ **Identify existing database and determine what can be done with it – that you are interested in!**
		+ **Get familiar with the data set – available variables**
		+ **Consider possible** **new** **questions that can be addressed**
		+ **Go to the literature**
			+ **How has database been used previously?**
			+ **What has already been answered?**
			+ **Develop a theoretical framework for your research**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Table 13.1**

**Steps in Finding Research Questions to Fit an Existing Database**

1. Choose a database.

2. Become thoroughly familiar with the database. Make a flow sheet of all variables and how they were measured.

3. Identify pairs or groups of variables whose association may be of interest.

4. Review the literature and consult experts to determine if these research questions would be novel and important.

5. Formulate specific hypotheses and settle on the statistical methods.

6. Analyze the data.
+ MEDB 5510 - Week 4


.footnote[Hearst et al. Research using existing data … In Hulley et al. (2001). Designing Clinical Research 2nd edition.]

---
#  Secondary Analysis 

+ **Chicken or the egg!**
	+ **Search for an existing database that will address the research question you are interested in**
		+ **Start with the research question you are interested in**
		+ **Have a list of variables that are relevant**
		+ **Have an idea of what databases are available**
		+ **Find out if there are special qualifications for working with the database**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Table 13.2**

**Steps in Finding Databases to Fit a Specified Research Question**

1. Choose a research question and review the literature thoroughly.

2. List combinations of predictor and outcome variables whose relationship might help answer the research question.

3. Identify databases that might include the variables of interest.

4. Become familiar with each of these databases and consult with individuals who know them well.

5. Choose the best database(s) and gain access to the data.

6. Formulate specific hypotheses and settle on the statistical methods.

7. Analyze the data.
+ MEDB 5510 - Week 4


.footnote[Hearst et al. Research using existing data … In Hulley et al. (2001). Designing Clinical Research 2nd edition]

---
#  Secondary Analysis 

+ **Sources – where to find out about them**
	+ **Journal articles / conference presentations**
	+ **Data libraries**
	+ **U.S. government**
		+ **Census Bureau**
		+ **National Center for Health Statistics (NCHS)**
		+ **Framingham Heart Study**
		+ **Multiple Risk Factor Intervention Trial (MRFIT)**
		+ **NIH Data Sharing Plan requirement**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Sources – where to find out about them**
	+ **Community-based data sets**
		+ **Evaluate patterns of utilization and clinical outcomes of medical treatment**
		+ **Examples**
			+ **Administrative and clinical database**
			+ **Registries**
		+ **Useful for**
			+ **Examining rare outcomes**
			+ **Assessing real-world utilization and effectiveness of an intervention**
			+ **Study effectiveness rather than efficacy**
		+ **Importance of replication**


.footnote[MEDB 5510 - Week 4]

---
#  Ancillary Studies 

+ **Adds new measurements to an existing/ongoing study**
	+ **Advantages**
		+ **Similar to advantages of secondary analysis**
		+ **Inexpensive & efficient**
		+ **Can be added to any type of study**
	+ **Disadvantages**
		+ **Not as valuable as if measures were part of original study**
			+ **Not a complete set of data**
		+ **Have no control over what the other measures are**
		+ **Need to get the buy-in of the primary investigators**


.footnote[MEDB 5510 - Week 4]

---
#  Ancillary Studies 

+ **Not unusual for additional measure to be added to longitudinal studies**
+ **How to get started**
	+ **Identify ongoing studies of interest**
		+ **Either predictor or outcome measures of interest**
		+ **NIH RePORTER (Research Portfolio Online Reporting Tool)**
		+ **ClinicalTrials.gov**
		+ **Pharmaceutical companies**
		+ **Contacting experts / researchers**
	+ **Get cooperation of investigators**


.footnote[MEDB 5510 - Week 4]

---
#  Ancillary Studies 

+ **How to get started (cont** **’** **d)**
	+ **Work out the logistics (measures, where to insert it, is there a cost associated with adding the measure?)**
	+ **Get all appropriate approvals (e.g., IRB to document change in data that are being collected)**
	+ **Work out what data from the main study you will have access to and how you will get the data you need**
	+ **Discuss and agree on issues such as manuscript publication and authorship**


.footnote[MEDB 5510 - Week 4]

---
#  Secondary Analysis 

+ **Examples of available secondary analysis data sets …**
	+ **MEPS (Medical Expenditure Panel Survey)**
	+ **YRBSS (Youth Risk Behavior Surveillance System)**
	+ **NSQIP (National Surgical Quality Improvement Proram)**
	+ **…**


.footnote[MEDB 5510 - Week 4]

---
#  #2 Assignment 

+ Go to a source of secondary data. Review available data types / topics on the data web site. Using the template provided in the Week 4 folder, write a brief description of a research topic you could address using this data source. Include in your description information on the variables that would be used . Use the hand-out with the list of possible web sites or your own source to identify a dataset you are interested in. 


.footnote[MEDB 5510 - Week 4]
