---
title: "Clinical Research Methods, Week 12"
author: "Steve Simon"
output:
  html_document: default
---

```{r echo=FALSE}
source(file="prelims.R", echo=FALSE)
```

Created: Friday, April 12, 2019

Updated: `r format(Sys.Date(), "%A, %B %d, %Y")`

Please complete all work by midnight, `r tue[12]` to receive full credit.

## Week 12: Hypothesis testing

### Learning objectives for this week

* To define Type I and II errors
* To describe the limitations of hypothesis testing

### Reading for this week

`r read_text("copyright")`

#### Required reading

* Gliner, Morgan, and Leech, Chapter 16.

### Recommended reading

Sackett DL. Why randomized controlled trials fail but needn’t: 2. Failure to employ physiological statistics, or the only formula a clinician-trialist is ever likely to need (or understand!). CMAJ. 2001;165(9):1226–1237. Available in [html format](http://www.cmaj.ca/content/165/9/1226.short) or [PDF format](http://www.cmaj.ca/content/165/9/1226.full.pdf).

Wasserstein RL, Lazar NA (2016) The ASA's Statement on p-Values: Context, Process, and Purpose, The American Statistician, 70:2, 129-133, DOI: 10.1080/00031305.2016.1154108. Availalble in [html format](https://amstat.tandfonline.com/doi/full/10.1080/00031305.2016.1154108) or [PDF format](https://amstat.tandfonline.com/doi/pdf/10.1080/00031305.2016.1154108).


### Discussion questions for this week

* D12-01. `r read_text("minute-paper")`

* D12-02. (Two points) 

* D12-EC. `r read_text("extra-credit")`
