---
title: "Clinical Research Methods, Week 9"
author: "Steve Simon"
output:
  html_document: default
---

```{r echo=FALSE}
source(file="prelims.R", echo=FALSE)
```

Created: Tuesday, March 19, 2019

Updated: `r format(Sys.Date(), "%A, %B %d, %Y")`

Please complete all work by midnight, `r mon[12]` to receive full credit.

## Week 10: Data collection

### Learning objectives for this week

* 

### Reading for this week

`r read_text("copyright")`

#### Required reading

* Gliner, Morgan, and Leech, Chapters 13, 15.

#### Recommended reading

* 

### Discussion questions for this week

* D10-01. `r read_text("minute-paper")`

* D10-02. (Two points) 

* D09-EC. `r read_text("extra-credit")`

### Old material

### Learning objectives

1. To discuss different methods of collecting data

2. To discuss when different data collections methods are most appropriate

3. To describe the advantages and disadvantages of different data collection methods

### Required reading

1. Chapters 13, 15

### Recommended reading

Bishop PA, Herron RL. Use and Misuse of the Likert Item Responses and Other Ordinal Measures. Int J Exerc Sci. 2015;8(3):297–302. Published 2015 Jul 1. Available in [html format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4833473/) or [PDF format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4833473/pdf/ijes_08_03_297.pdf).

Dearnley C. A reflection on the use of semi-structured interviews. Nurse Researcher 2005: 13(1); 19-28. This article is behind a paywall and can be downloaded from the Canvas website.

Diaz A, Peake K, Nucci-Sack A, Shankar V. Comparison of Modes of Administration of Screens to Identify a History of Childhood Physical Abuse in an Adolescent and Young Adult Population. Ann Glob Health. 2017;83(5-6):726–734. doi:10.1016/j.aogh.2017.10.023. Available in [html format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5739060/) or [PDF format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5739060/pdf/nihms917351.pdf).

Harrison C. Questionnaire Design Tip Sheet. Harvard University Program on Survey Research. Available in [PDF format](https://psr.iq.harvard.edu/files/psr/files/PSRQuestionnaireTipSheet_0.pdf).

Jamshed S. Qualitative research method-interviewing and observation. J Basic Clin Pharm. 2014;5(4):87–88. doi:10.4103/0976-0105.141942. Available in [html format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4194943/) or [PDF format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4194943/pdf/JBCP-5-87.pdf).

Kallio H, Pietilä AM, Johnson M, Kangasniemi M. Systematic methodological review: developing a framework for a qualitative semi-structured interview guide. J Adv Nurs. 2016 Dec; 72(12): 2954-2965. doi: 10.1111/jan.13031. This article is behind a paywall and can be downloaded from the Canvas website.

McLeod S. The Interview Method. Simply Psychology, 2014. Available in [html format](https://www.simplypsychology.org/interviews.html) or [PDF format](https://www.simplypsychology.org/simplypsychology.org-interview-method.pdf).

Ochieng NT, Wilson K, Derrick CJ, Mukherjee N. The use of focus group discussion methodology: Insights from two decades of application in conservation. Methods Ecol Evol. 2018; 9: 20– 32. doi: 10.1111/2041-210X.12860. Available in [html format](https://doi.org/10.1111/2041-210X.12860) or [PDF format](https://besjournals.onlinelibrary.wiley.com/doi/epdf/10.1111/2041-210X.12860).

Pew Research Center. Questionnaire Design. Available in [html format](https://www.pewresearch.org/methods/u-s-survey-research/questionnaire-design/).

Tausch AP, Menold N. Methodological Aspects of Focus Groups in Health Research: Results of Qualitative Interviews With Focus Group Moderators. Glob Qual Nurs Res. 2016;3:2333393616630466. Published 2016 Mar 14. doi:10.1177/2333393616630466. Avialable in [html format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5342644/) or [PDF format](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5342644/pdf/10.1177_2333393616630466.pdf).

Vanderbilt University. REDCap Videos. Available in [html format](https://projectredcap.org/resources/videos/) but note that the individual links are to mp4 video files.

WikiHow. How to Run a Focus Group. Available in [html format](https://www.wikihow.com/Run-a-Focus-Group).

Whiting LS. Nursing Standard 2008: 22(23); 35-40. This article is behind a paywall and can be downloaded from the Canvas website.


#### Older references

Cohen D, Crabtree B. "Qualitative Research Guidelines Project." Robert Wood Johnson Foundation, July 2006. Available in [html format](http://www.qualres.org/HomeFocu-3647.html)

Cummings, S.R. & Hulley, S.B. (2007). Chapter 15 "Designing questionnaires and interviews." In S.B. Hulley, S.R. Cummings, W.S. Browner, D. Grady, & T.B. Newman (eds), Designing Clinical Research, 3rd edition. Philadelphia: Lippincott Williams & Wilkins.

Centers for Disease Control and Prevention. Checklist to Evaluate the Quality of Questions. Available in [PDF format](https://www.cdc.gov/healthyyouth/evaluation/pdf/brief15.pdf).

### Assignment

1. Further refine your list of variables by specifying how each will be measured. Wherever possible, include the name of a specific measure that would be appropriate. Be as specific as you can in terms of what variables/measures will be obtained. This assignment should give you a final draft of the "measures" description included in the Methods section of your research proposal. What you submit for this assignment should reflect the feedback you received on the last assignment.

2. Prepare for next week's session

### Discussion questions

1. Discuss the data collection method that is appropriate for your research proposal.

2. Discuss the procedure you would propose to collect data for your research proposal.


