---
title: "Video 10 - Data collection"
author: "Steve Simon"
output: 
  powerpoint_presentation:
    reference_doc: ../doc/template.pptx
    slide_level: 3
---

```{r echo=FALSE}
source("prelims.R", echo=FALSE)
```

***
`r read_text("objectives10")`

***
`r read_text("readings10")`

***
### Data Collection Techniques 


(assets/img/image1.png)




***
### Data Collection Techniques 

+ Standardized vs Investigator-Developed Instruments
	+ Development and Use
	+ Evidence to support investigator-developed instruments




***
### Data Collection Techniques 

+ Researcher-Observed Measures
	+ Naturalness of the setting
	+ Observer “participation”
	+ Amount of detail
	+ Breadth of coverage




***
### Data Collection Techniques 

+ Tests and Documents
	+ Standardized tests
		+ Norm referenced test
		+ Criterion referenced test
	+ Achievement tests
	+ Performance and Authentic assessments
	+ Aptitude tests
	+ Documents
	+ Content analysis




***
### Data Collection Techniques 

+ Self-Report Measures
	+ Standardized Personality Inventories
	+ Attitudes / Beliefs scales
		+ Likert scale
		+ Semantic differential scale
	+ Questionnaires
		+ How delivered / administered
		+ Item types
	+ Interviews
	+ Focus groups




***
### Descriptive Research 

+ Surveys
	+ Methods
		+ Interview
		+ Questionnaires
	+ Design of surveys
		+ Research question
		+ Review of existing instruments
		+ Process of designing survey




***
### Data Collection Techniques 

+ Surveys
	+ Survey question format –
		+ Open-ended
		+ Close-ended
	+ Wording of questions
	+ Scales
		+ Scale of measurement
		+ Response options




***
### Data Collection Techniques 

+ Open-ended vs Close-ended

(assets/img/image2.png)


.footnote[Sim & Wright, 2002]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Likert

(assets/img/image3.jpeg)


.footnote[Portney & Watkins, 2009]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Likert

(assets/img/image4.png)


.footnote[Sim & Wright, 2002]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Likert

(assets/img/image5.jpeg)


.footnote[Sim & Wright, 2002]

***
### Data Collection Techniques 

+ Surveys – Response Options

(assets/img/image6.png)


.footnote[Sim & Wright, 2002]

***
### Data Collection Techniques 

+ Surveys – Response Options

(assets/img/image7.png)


.footnote[Sim & Wright, 2002]

***
### Data Collection Techniques 

+ Surveys – Response Options

(assets/img/image8.png)


.footnote[Sim & Wright, 2002]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Semantic Differential

(assets/img/image9.jpeg)


.footnote[Portney & Watkins, 2009]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Semantic Differential

(assets/img/image10.png)


.footnote[Portney & Watkins, 2009]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Visual Analogue Scale (VAS)

(assets/img/image11.jpeg)


.footnote[Portney & Watkins, 2009]

***
### Data Collection Techniques 

+ Surveys – Response Options
	+ Numerical Rating Scale

(assets/img/image12.png)


.footnote[Sim & Wright, 2002]

***
### Descriptive Research 

+ Surveys
	+ Pit-falls and words of caution
		+ How responses are recorded
		+ Wording of items
			+ Literacy level
			+ “ Loaded ” wording
		+ Complexity of items
			+ More than 1 “ unit ” in a single item
			+ Clearly stated terms




***
### Data Collection Techniques 

+ Surveys
(assets/img/image13.jpeg)




***
### Data Collection Techniques 

+ Surveys – Example
	+ Using a scale of 0 to 100, please indicate the percentage of time you take all the doses of your medicine?
	+ … take all the pills in each of your doses?
	+ … take all doses on the prescribed schedule?
	+ … follow all special instructions …
	+ … make sure you refill all of your medications on time?




***
### Data Collection Techniques 

+ Process of developing a survey
	+ List of measures/variables
	+ What ’ s already available?
	+ Put the pieces together
	+ Test and revise as needed
	+ Final check – do you really need all of the items?
+ Analysis of survey data




***
### Data Collection & Coding 


(assets/img/image14.png)




***
### Data Collection & Coding 

+ Initial Steps
	+ Planning the study
	+ Pilot testing
	+ Data collection
		+ Check for completeness if possible




***
### Data Collection & Coding 

+ Data Coding, Entry, and Checking
	+ Guidelines
		+ Mutually exclusive levels
		+ Code for maximum information
		+ Record is as complete as possible
		+ Consistency
	+ Data entry form
	+ Checking entry




***
### Data Collection & Coding 


(assets/img/image15.png)




***
### Data Collection & Coding 

+ Data Entry into Statistical Program
	+ Layout of data sheet
	+ Variable names
	+ Labeling
		+ Variables
		+ Values
	+ Codebook / documentation




***
### Data Collection & Coding 

+ Data Summation
	+ Descriptive information
		+ Categorical variables
		+ Continuous variables
	+ Data checking – part 2




***
### Data Collection & Coding 


(assets/img/image16.png)




***
### Assignment #8 

+ Further refine your list of variables by specifying how each will be measured. Wherever appropriate, include the name of a specific measure. Do this by building onto the methods section of your research proposal draft. 



***
`r read_text("hw10", fri[10])`

***
`r read_text("discussion10", fri[10])`

***

### Additional slides