---
title: "Video 2"
author: "Steve Simon"
output: ioslides_presentation
---

```{r echo=FALSE}
source("prelims.R", echo=FALSE)
```

***
`r read_text("objectives02")`

***
`r read_text("readings02")`

***
`r read_text("hw02", fri[2])`

***
`r read_text("discussion02", fri[2])`

***
`r read_text("objectives03")`

***
`r read_text("readings03")`

***
`r read_text("hw03", fri[3])`

***
`r read_text("discussion03", fri[3])`

***
`r read_text("objectives04")`

***
`r read_text("readings04")`

***
`r read_text("hw04", fri[4])`

***
`r read_text("discussion04", fri[4])`

***
`r read_text("objectives05")`

***
`r read_text("readings05")`

***
`r read_text("hw05", fri[5])`

***
`r read_text("discussion05", fri[5])`

***
`r read_text("objectives06")`

***
`r read_text("readings06")`

***
`r read_text("hw06", fri[6])`

***
`r read_text("discussion06", fri[6])`

***
`r read_text("objectives07")`

***
`r read_text("readings07")`

***
`r read_text("hw07", fri[7])`

***
`r read_text("discussion07", fri[7])`

***
`r read_text("objectives08")`

***
`r read_text("readings08")`

***
`r read_text("hw08", fri[8])`

***
`r read_text("discussion08", fri[8])`

***
`r read_text("objectives09")`

***
`r read_text("readings09")`

***
`r read_text("hw09", fri[9])`

***
`r read_text("discussion09", fri[9])`

***
`r read_text("objectives10")`

***
`r read_text("readings10")`

***
`r read_text("hw10", fri[10])`

***
`r read_text("discussion10", fri[10])`

***
`r read_text("objectives12")`

***
`r read_text("readings12")`

***
`r read_text("hw12", fri[12])`

***
`r read_text("discussion12", fri[12])`

***
`r read_text("objectives13")`

***
`r read_text("readings13")`

***
`r read_text("hw13", fri[13])`

***
`r read_text("discussion13", fri[13])`

***
`r read_text("objectives14")`

***
`r read_text("readings14")`

***
`r read_text("hw14", fri[14])`

***
`r read_text("discussion14", fri[14])`

***
`r read_text("objectives15")`

***
`r read_text("readings15")`

***
`r read_text("hw15", fri[15])`

***
`r read_text("discussion15", fri[15])`

***
`r read_text("objectives16")`

***
`r read_text("readings16")`

***
`r read_text("hw16", fri[16])`

***
`r read_text("discussion16", fri[16])`

***

### Additional slides